### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by mgermerie** [mgermerie/itowns-demo-3dtiles#1]
- [ ] Move camera to a newly added tileset
- [ ] Move the known_dataset to the data server
- [ ] Publish on production server
